"""
Threat classification taxonomies and severity definitions for SIH 2026.
"""

from enum import Enum

class ThreatCategory(str, Enum):
    DDOS = "VOLUMETRIC_PROTOCOL_DDOS"
    C2 = "BOTNET_C2_BEACONING"
    DNS = "DGA_DNS_TUNNELLING"
    ENCRYPTED = "ENCRYPTED_TRAFFIC_ANALYSIS"
    RECON = "RECONNAISSANCE_PORT_SCAN"
    EXFILTRATION = "DATA_EXFILTRATION"

class ThreatClass(str, Enum):
    # Category A: Volumetric / Protocol DDoS
    DDOS_SYN_FLOOD = "DDoS_SYN_FLOOD"
    DDOS_UDP_FLOOD = "DDoS_UDP_FLOOD"
    DDOS_AMPLIFICATION = "DDoS_AMPLIFICATION"
    DDOS_SPOOFED_SOURCE = "DDoS_SPOOFED_SOURCE"

    # Category B: Botnet C2 Beaconing
    C2_BEACONING = "C2_BEACONING"
    C2_PERIODIC_HEARTBEAT = "C2_PERIODIC_HEARTBEAT"

    # Category C: DGA Domains / DNS Tunnelling
    DGA_DOMAIN = "DGA_DOMAIN"
    DNS_TUNNELLING = "DNS_TUNNELLING"
    SUSPICIOUS_DNS = "SUSPICIOUS_DNS"

    # Category D: Encrypted Traffic Analysis (Metadata Only)
    TLS_METADATA_ANOMALY = "TLS_METADATA_ANOMALY"
    SUSPICIOUS_JA3_FINGERPRINT = "SUSPICIOUS_JA3_FINGERPRINT"
    ENCRYPTED_BURST_PATTERN = "ENCRYPTED_BURST_PATTERN"

    # Category E: Reconnaissance / Port Scanning
    PORT_SCAN = "PORT_SCAN"
    HOST_SCAN = "HOST_SCAN"
    RECONNAISSANCE = "RECONNAISSANCE"
    HORIZONTAL_SCAN = "HORIZONTAL_SCAN"
    VERTICAL_SCAN = "VERTICAL_SCAN"

    # Category F: Potential Data Exfiltration
    DATA_EXFILTRATION = "DATA_EXFILTRATION"
    POTENTIAL_DATA_EXFILTRATION = "POTENTIAL_DATA_EXFILTRATION"

class SeverityLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class DetectionEngineType(str, Enum):
    RULE_ENGINE = "RULE_ENGINE"
    STATISTICAL_ANOMALY = "STATISTICAL_ANOMALY"
    RANDOM_FOREST = "RANDOM_FOREST"
    ISOLATION_FOREST = "ISOLATION_FOREST"
    HYBRID_ENSEMBLE = "HYBRID_ENSEMBLE"
